### ISSUE TITLE
Can use with file (ex: pdf, document, audio,...)?

### ISSUE THREAD

**Issue by thanhtuht** [ming-xi/MXMediaPicker#1]
In this library , we can use only images/video
Can we use it for users can pick any files (PDF, documents,audio,...)???

**Comment by ArchangelXu** [comment]
@thanhtuht Thank you for asking~
For now... yes. Because you if you want a file picker, SAF should be ok, see [https://stackoverflow.com/questions/63815276/how-to-get-dir-file-list-in-android-11](https://stackoverflow.com/questions/63815276/how-to-get-dir-file-list-in-android-11)
The main idea of this library is to provide a flexible way to choose videos and images.

**Comment by thanhtuht** [comment]
Thank you for your reply, hope in next version, this can support file picker too, not only media only
